<table width=100%; style="background-color:#caf0fa";>
    <tr style="background-color:#caf0fa">
        <td>
            <h1 style="text-align:right">
                Python for Data Science Training - Week 2
            </h1>
        </td>
        <td>
            <img src="../img/jica-logo.png" alt = "JICA Training" style = "width: 100px;"/>
        </td>
    </tr>
</table>

# Today's Contents
1. Data types
2. How to install and import libraries
3. Numpy
4. Pandas - Intro
---

# 1. Data Types

| Numeric | Text | Sequence/Dictionary | Boolean |
| --- | --- | --- | --- |
| `int` | `str` | `list` | `bool` |
| `float` | . | `tuple` | . |
| . | . | `range` | . |
| . | . | `dict` | . |

### Numeric

In [1]:
# Integer
type(1)

int

In [2]:
# Float
type(1.1)

float

In [3]:
type(1.0)

float

In [4]:
type(1.)

float

In [5]:
mix_of_int_and_float = 1 + 1.5
print(mix_of_int_and_float)
print('Data Type: ', type(mix_of_int_and_float))

2.5
Data Type:  <class 'float'>


In [6]:
# You can explititly assign number
int(5)

5

In [7]:
float(1.5)

1.5

In [8]:
# Float can be forced to be integer
int(5.5)

5

In [9]:
# Integer can be forced to be integer
float(4)

4.0

### Text

In [10]:
type('My favorite number... ')

str

In [11]:
# String and number cannot be merged
'My favorite number is... ' + 7

TypeError: can only concatenate str (not "int") to str

In [12]:
# A solution is to change the number to string
'My favorite number is... ' + str(7)

'My favorite number is... 7'

### List
- `[ ]`
- `list([ ])`

In [13]:
# Case 1 - with bracket
list_number = [1, 2, 3, 4, 5]
list_number

[1, 2, 3, 4, 5]

In [14]:
list_num_and_str = [1, 2, 3, 4, 't']
list_num_and_str

[1, 2, 3, 4, 't']

In [15]:
# Case 2- with `list`
list_text = list(['abc', 'cde', 'efg'])
list_text

['abc', 'cde', 'efg']

In [16]:
print(type(list_number))
print(type(list_num_and_str))
print(type(list_text))

<class 'list'>
<class 'list'>
<class 'list'>


### Tuple
- ( )

In [17]:
this_is_tuple = (1, 2, 3)
print(this_is_tuple)
print(type(this_is_tuple))

(1, 2, 3)
<class 'tuple'>


### Dictionary
- `{key: value}`

In [18]:
my_dict = {'FirstName':'Hiroyuki'}
print(my_dict)
print(type(my_dict))

{'FirstName': 'Hiroyuki'}
<class 'dict'>


In [19]:
# You can find keys
my_dict.keys()

dict_keys(['FirstName'])

In [20]:
# You can also find values
my_dict.values()

dict_values(['Hiroyuki'])

In [21]:
# Multiple keys and values can be assigned.
my_new_dict = {'FirstName':'Hiroyuki', 'LastName':'Yokoi'}
print(my_new_dict.keys())
print(my_new_dict.values())

dict_keys(['FirstName', 'LastName'])
dict_values(['Hiroyuki', 'Yokoi'])


In [22]:
# You can add another key and value
my_dict['LastName'] = 'Yokoi'
print(my_dict)

{'FirstName': 'Hiroyuki', 'LastName': 'Yokoi'}


In [23]:
# Without creating a new dictionary, you can update the dictionary by `.update` method
my_dict.update({'FullName':'Hiroyui Yokoi'})

In [24]:
my_dict

{'FirstName': 'Hiroyuki', 'LastName': 'Yokoi', 'FullName': 'Hiroyui Yokoi'}

### Boolean
- `True` or `False`

In [25]:
True

True

In [26]:
False

False

In [27]:
# Python is case sensitive language. For example, "true" does not work
true

NameError: name 'true' is not defined

Let's see if True equals False.  
Note that in Python `==` means left-hand and right-hand side is exactly equal.  
Don't mess up with `=`, which assigns a variable.

In [28]:
True == False

False

In [29]:
True == True

True

In [30]:
False == False

True

In [31]:
False == True

False

In [32]:
# In Python, True is considered as 1, while False is as 0.
int(True)

1

In [33]:
int(False)

0

In [34]:
True + True

2

In [35]:
False + False

0

# 2. How to install and load libraries
Other than [Python built-in functions](https://docs.python.org/3/library/functions.html), you always need to import relevant libraries. If a library is not installed to your computer, you should install the library by calling:
```python
conda install xxxx
```
(It is also possible to install with:
```python
pip install xxxx
```
but this does not consider dependencies, thus `conda install xxxx` is recommended.)   

After installation, you call the library with:
```python
import xxxx
```


### Install a library
1. Google `conda install xxxx` (xxxx should be a specific library) and find an installation page in "https://anaconda.org".
2. Under this page, you'll find a text like: **To install this package with conda run: ** `conda install -c anaconda numpy`
3. Copy and paste to **Command**(Windows)/**Terminal**(Mac).

Alternatively, you can just run a command in a jupyter notebok by: `!conda install -c anaconda numpy`

In [36]:
# !conda install -c anaconda numpy

### Import a library

In [37]:
# import white space library
import numpy

In [38]:
type(numpy)

module

In [39]:
# also can be used `as` for a shorthand name
import numpy as np

In [40]:
type(np)

module

In [41]:
# sometimes a library has "deep" module, and a deeper method can be called with the combination of dot.
import matplotlib.pyplot as plt
type(plt)

module

In [42]:
# Several libraries can be loaded in the same cell.
import numpy as np
import pandas as pd

# 3. Numpy
Numpy is the most popular and famous library in Python. Many many libraries are built upon Numpy.

In [43]:
# numpy array
arr = [1, 2, 3, 4]
np_arr = np.array(arr)
print(np_arr)
print('Type is: ', type(np_arr))

[1 2 3 4]
Type is:  <class 'numpy.ndarray'>


In [44]:
# Shape is (row, column)
np_arr.shape

(4,)

In [45]:
# two dimensional aray
arr_two_dim = [[1, 2, 3], [5, 6, 7]]
np_arr_two_dim = np.array(arr_two_dim)
print(np_arr_two_dim)
print('Type is: ', type(np_arr_two_dim))

[[1 2 3]
 [5 6 7]]
Type is:  <class 'numpy.ndarray'>


In [46]:
np_arr_two_dim.shape # two rows and three columns

(2, 3)

In [47]:
np_arr_two_dim.ndim # Show dimension

2

In [48]:
np_arr_two_dim.dtype # numeric type

dtype('int64')

In [49]:
# select random number
np_random = np.random.randint(low = 0, high = 100, size = 10)
np_random

array([26, 81, 75, 17, 23,  4,  2, 40, 66,  5])

In [50]:
# show shape
np_random.shape  # row 10, col none

(10,)

In [51]:
# Find max number
np.max(np_random)

81

In [52]:
# Find min number
np.min(np_random)

2

In [53]:
# Show mean value
np.mean(np_random)

33.9

In [54]:
# Same method
np_random.mean()

33.9

In [55]:
# Show median value
np.median(np_random)

24.5

In [56]:
# Standard deviation
np.std(np_random)

28.61625412243888

In [57]:
# Variance
np.var(np_random)

818.8900000000001

In [58]:
# simple calculation: square root of variance
np.sqrt(np.var(np_random))

28.61625412243888

In [59]:
# simple calculation: variance is calculated by squaring standard deviation
np.std(np_random) ** 2

818.8900000000001

## Indexing
An index is a sequential number of a variable, which starts from **0** in Python.

In [60]:
# Indexing: make sure it starts from 0.
print(np_random)

[26 81 75 17 23  4  2 40 66  5]


In [61]:
print(np_random[0])

26


In [62]:
print(np_random[1])

81


In [63]:
print(np_random[2])

75


In [64]:
# Index of the last item is: -1
print(np_random[-1])

5


In [65]:
print(np_random[-2])

66


### For loop
It is tedious to type the same command again and again. If there is a repetition in the command, you can run **for loop**.


```python
for any_name in list_variable:
    *do your function
```

In [66]:
# Show the list variable again.
np_random

array([26, 81, 75, 17, 23,  4,  2, 40, 66,  5])

In [67]:
# Show individual item with for-loop
for item in np_random:
    print(item)

26
81
75
17
23
4
2
40
66
5


In [68]:
# Distinguishing each variable with index:
for i, item in enumerate(np_random):
    print(f'Index is {i} and Number is {item}')

Index is 0 and Number is 26
Index is 1 and Number is 81
Index is 2 and Number is 75
Index is 3 and Number is 17
Index is 4 and Number is 23
Index is 5 and Number is 4
Index is 6 and Number is 2
Index is 7 and Number is 40
Index is 8 and Number is 66
Index is 9 and Number is 5


In [69]:
# Another example
name_list = ['Suzuki', 'Yamada', 'Kobayashi']
for name in name_list:
    print('My name is ', name)

My name is  Suzuki
My name is  Yamada
My name is  Kobayashi


In [70]:
# zip function: zipping two lists
first_name = ['Kazu', 'Hide', 'Shinji']
last_name = ['Miura', 'Nakata', 'Kagawa']

for first, last in zip(first_name, last_name):
    print(first, last)

Kazu Miura
Hide Nakata
Shinji Kagawa


In [71]:
# range function: create sequence
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


### List Comprehension - Quicker way to apply for-loop
```python
[element for element in list_variable]
```

In [72]:
# Quicker way - List comprehension
[name for name in name_list]

['Suzuki', 'Yamada', 'Kobayashi']

# グループワーク

### ワーク1: for loopを使って次のように文字をプリントしてください

```python
"1 番目の人です。"
"2 番目の人です。"
"3 番目の人です。"
"4 番目の人です。"
"5 番目の人です。"
```

In [73]:
# TODO


### ワーク2: 
1. 学生の時に聞いていたミュージシャンの名前を３つリストとして書き出してください。
2. そのミュージシャンの好きな曲のタイトルをそれぞれ３つリストとして書き出してください。
3. for loopを使って以下のように文字をプリントしてください。

```python
"私が好きなミュージシャンは●●です。そのうち、好きな曲は■■です。"  
"私が好きなミュージシャンは○○す。そのうち、好きな曲は□□です。"  
"私が好きなミュージシャンは▲▲です。そのうち、好きな曲は△△です。 "
```

In [74]:
# TODO
musician_name = 
music_titles = 

SyntaxError: invalid syntax (<ipython-input-74-bb3ccbf6d082>, line 2)

### ワーク3:
上のリストを使って、以下のように変化させてください。<br>
ポイント：１番目、２番目、３番目というシークエンスが加わりました。<br><br>
```python
"私が1番目に好きなミュージシャンは●●です。そのうち、好きな曲は■■です。"
"私が2番目に好きなミュージシャンは○○す。そのうち、好きな曲は□□です。"
"私が3番目に好きなミュージシャンは▲▲です。そのうち、好きな曲は△△です。"
```

In [75]:
# TODO


### Conditional for-loop
1. Two conditions
```python
    for element in list_variable:
        if *condition*:  
            *do_something
       else:
            *do_the_rest
```
2. More than two conditions
```python
    for element in list_variable:
        if *condition*:  #  First condition
            *do_something
       elif *another condition*:  #  Second condition
            *do_another
       else:
            *do_the_rest
```

### Append method
It is useful to store variable applied to a specific condition. First, you need to provide a empty list, then you need to be explicit to append a variable to the list.
```python
    empty_list_1 = []
    empty_list_2 = []
    for element in list_variable:
        if *condition*:
            *do_something
            empty_list_1.append(element) # an element meeting the condition is appended to the empty_list_1
        else:
            *do_the_rest
            empty_list_2.append(element) # an element NOT meeting the condition is appended to the empty_list_2
            
```

In [76]:
# Show the list variable again.
np_random

array([26, 81, 75, 17, 23,  4,  2, 40, 66,  5])

In [77]:
# two conditions
more_than_50_list = []
less_than_50_list = []

for element in np_random:
    if element > 50:
        # If element is more than 50, store the variable to the list of more_than_50_list
        more_than_50_list.append(element) 
    else:
        # If above condition is not met, store the remaining to the list of less_than_50_list
        less_than_50_list.append(element) 

In [78]:
print('More than 50\n', more_than_50_list)
print('Less than 50\n', less_than_50_list)

More than 50
 [81, 75, 66]
Less than 50
 [26, 17, 23, 4, 2, 40, 5]


In [79]:
# multiple conditions
small_number_list = []
mid_number_list = []
large_number_list = []

for element in np_random:
    if element > 30 and element < 60:
        #  Store number between 30 and 60 to mid_number_list
        mid_number_list.append(element) 
    elif element >= 60:
        #  Store number more than 60 to large_number_list
        large_number_list.append(element)
    else:
        small_number_list.append(element)

In [80]:
print('Small Number (0-30):\n', small_number_list)
print('Mid Number (30-60):\n', mid_number_list)
print('Large Number (60-100):\n', large_number_list)

Small Number (0-30):
 [26, 17, 23, 4, 2, 5]
Mid Number (30-60):
 [40]
Large Number (60-100):
 [81, 75, 66]


# 4. Pandas - Intro
<img src="https://upload.wikimedia.org/wikipedia/commons/0/0f/Grosser_Panda.JPG" alt="Panda" style = "width: 250px;">

Pandas is another most famous library which handles **dataframe**, in other words, a table. Pandas is very powerful to work with any kind of tables which may have numbers and text. Let's take a quick look.

In [81]:
# As convention, pandas is called as pd for a shorthand name.
import pandas as pd

We'll reveiw the following [excel version of JICA's annual report](https://www.jica.go.jp/about/report/2020/ku57pq00002mxr2q-att/chart01_01.xls). Look into **"P16　図表-3"**.


なお、ローカル環境でPythonを動かしている方は、以下でエラーが出る可能性があります。エラーの原因はPandasでエクセルを読み込むための、`xlrd`というdependencyファイルがないためです。同様のエラーが出た方は、以下をコマンドで実行ください。

`conda install -c anaconda xlrd`

In [82]:
# Let's take a quick look at JICA's annual report.
url = 'https://www.jica.go.jp/about/report/2020/ku57pq00002mxr2q-att/chart01_01.xls'
scheme_wise_results = pd.read_excel(url)
scheme_wise_results

Unnamed: 0                             Unnamed: 1  \
0          NaN          図表-2　 日本のODA実績［2019年（暦年）、暫定値］   
1          NaN                                    NaN   
2          NaN  　　　　　　　　　　　　　　　 援助実績（2019年（暦年））\n援助形態   
3          NaN                                    NaN   
4          NaN                                    ODA   
5          NaN                                    NaN   
6          NaN                                    NaN   
7          NaN                                    NaN   
8          NaN                                    NaN   
9          NaN                                    NaN   
10         NaN                             ODA計(支出総額)   
11         NaN                   名目GNI速報値（10億ドル、10億円）   
12         NaN                       対ＧＮI比（％）：（純額ベース）   
13         NaN                                    NaN   
14         NaN                                    （注）   
15         NaN                                    NaN   
16         NaN                                    NaN   
17         NaN                                    NaN   
18         NaN                                    NaN   
19         NaN                                    NaN   
20         NaN                                    NaN   
21         NaN                                    NaN   
22         NaN                                      ※   

                 Unnamed: 2  \
0                       NaN   
1                       NaN   
2                       NaN   
3                       NaN   
4                    二国間ODA   
5                       NaN   
6                       NaN   
7                       NaN   
8            二国間ODA計（純額ベース）   
9   国際機関向け拠出・出資等計（総額・純額ベース）   
10                      NaN   
11                      NaN   
12                      NaN   
13                      NaN   
14                        1   
15                        2   
16                        3   
17                        4   
18                        5   
19                        6   
20                        7   
21                        8   
22    技術協力に行政経費・開発啓発費を含みます。   

                                           Unnamed: 3 Unnamed: 4  \
0                                                 NaN        NaN   
1                                                 NaN        NaN   
2                                                 NaN        NaN   
3                                                 NaN        NaN   
4                                                  贈与     無償資金協力   
5                                                 NaN      技術協力※   
6                                                 贈与計        NaN   
7                                           政府貸付等（純額）        NaN   
8                                                 NaN        NaN   
9                                                 NaN        NaN   
10                                                NaN        NaN   
11                                                NaN        NaN   
12                                                NaN        NaN   
13                                                NaN        NaN   
14  上記には卒業国向けの援助を含んでいます。卒業国向け援助を除いた実績の詳細は、別冊資料編の表1...        NaN   
15  DAC諸国以外の卒業国で支出実績を有するのは次の16カ国・地域：アラブ首長国連邦、ウルグアイ...        NaN   
16    2019年DAC指定レート: 1ドル=109.0459円（2018年比、1.3919円の円高）        NaN   
17                       四捨五入の関係上､各形態の計が一致しないことがあります｡        NaN   
18                     債務救済は、商業上の債務の免除であり、債務繰延は含みません。        NaN   
19  従来、国際機関を通じた贈与は「国際機関向け拠出・出資等」として計上してきましたが、2006年...        NaN   
20  技術協力に含めてきたNGO事業補助金については、2011年実績より各国の無償資金協力に含める...        NaN   
21                       本データは外務省提供によるもの。前年実績は確定値を掲載。        NaN   
22                                                NaN        NaN   

      Unnamed: 5 Unnamed: 6 Unnamed: 7 Unnamed: 8 Unnamed: 9 Unnamed: 10  \
0            NaN        NaN        NaN        NaN        NaN         NaN   
1            NaN        NaN        NaN        NaN        NaN         NaN   
2   ドル･ベース(百万ドル)        NaN  

- The table is ugly to read. Use `.head()` method, which shows the first 5 rows.
- `pd.read_excel` reads the first sheet if not explicitly specified. Thus, you need to specify `sheet_name`.

In [83]:
scheme_wise_results.head()

Unnamed: 0                             Unnamed: 1 Unnamed: 2 Unnamed: 3  \
0         NaN          図表-2　 日本のODA実績［2019年（暦年）、暫定値］        NaN        NaN   
1         NaN                                    NaN        NaN        NaN   
2         NaN  　　　　　　　　　　　　　　　 援助実績（2019年（暦年））\n援助形態        NaN        NaN   
3         NaN                                    NaN        NaN        NaN   
4         NaN                                    ODA     二国間ODA         贈与   

  Unnamed: 4    Unnamed: 5 Unnamed: 6 Unnamed: 7 Unnamed: 8 Unnamed: 9  \
0        NaN           NaN        NaN        NaN        NaN        NaN   
1        NaN           NaN        NaN        NaN        NaN        NaN   
2        NaN  ドル･ベース(百万ドル)        NaN        NaN   円ベース(億円)        NaN   
3        NaN           実　績       前年実績     増減率（%）        実　績       前年実績   
4     無償資金協力       2553.02    2639.75       -3.3    2783.97    2915.28   

  Unnamed: 10  Unnamed: 11  
0         NaN          NaN  
1         NaN          NaN  
2         NaN       構成比（％）  
3      増減率（%）  ODA計(純額ベース)  
4        -4.5           22

In [84]:
# Let's make sure you assign the sheet_name
scheme_wise_results = pd.read_excel(url, sheet_name='P16　図表-3', header=4) # header= is from which rows you want to read.

In [85]:
scheme_wise_results.head()

Unnamed: 0                                       形態       金額
0         NaN                                   技術協力※１   1751.0
1         NaN                                 有償資金協力※2  15232.0
2         NaN                                 無償資金協力※3    856.0
3         NaN                                      NaN      NaN
4         NaN  ※１　有償資金協力勘定予算による技術支援等を含み、管理費を除く技術協力経費実績      NaN

Sounds like that you read the correct sheet, but this is still little ugly.  
Let's extract what you want - rows 0-2 and columns of 形態 and 金額

In [86]:
# iloc method can extract what you need to use. In this case, rows should be up to 2, columns should be after 形態.
scheme_wise_results = scheme_wise_results.iloc[:3, 1:] #  :3 = 0-2, 1: = select all after index 1

In [87]:
scheme_wise_results

形態       金額
0    技術協力※１   1751.0
1  有償資金協力※2  15232.0
2  無償資金協力※3    856.0

---
今週は以上。
  
  
来週はPandasをDeep Dive！
関心ある人は[10 minutes to Pandas](https://pandas.pydata.org/pandas-docs/stable/user_guide/10min.html)をみてください。

---

In [88]:
# This cell is to create a config file.
# Hiding this cell for authority

# Hiding celll from https://gist.github.com/Zsailer/5d1f4e357c78409dd9a5a4e5c61be552
from IPython.display import HTML
from IPython.display import display

# Taken from https://stackoverflow.com/questions/31517194/how-to-hide-one-specific-cell-input-or-output-in-ipython-notebook
tag = HTML('''<script>
code_show=true; 
function code_toggle() {
    if (code_show){
        $('div.cell.code_cell.rendered.selected div.input').hide();
    } else {
        $('div.cell.code_cell.rendered.selected div.input').show();
    }
    code_show = !code_show
} 
$( document ).ready(code_toggle);
</script>
Creating requirements.txt file. To show/hide this cell's raw code input, click <a href="javascript:code_toggle()">here</a>.''')
display(tag)

############### Write code below ##################
# Config file to freeze packages in a notebook
# from https://stackoverflow.com/questions/40428931/package-for-listing-version-of-packages-used-in-a-jupyter-notebook
import pkg_resources
import types

def get_requirements():
    def get_imports():
        for name, val in globals().items():
            if isinstance(val, types.ModuleType):
                # Split ensures you get root package, 
                # not just imported function
                name = val.__name__.split(".")[0]

            elif isinstance(val, type):
                name = val.__module__.split(".")[0]

            # Some packages are weird and have different
            # imported names vs. system/pip names. Unfortunately,
            # there is no systematic way to get pip names from
            # a package's imported name. You'll have to add
            # exceptions to this list manually!
            poorly_named_packages = {
                "PIL": "Pillow",
                "sklearn": "scikit-learn"
            }
            if name in poorly_named_packages.keys():
                name = poorly_named_packages[name]

            yield name
    imports = list(set(get_imports()))

    # The only way I found to get the version of the root package
    # from only the name of the package is to cross-check the names 
    # of installed packages vs. imported packages
    requirements = []
    for m in pkg_resources.working_set:
        if m.project_name in imports and m.project_name!="pip":
            requirements.append((m.project_name, m.version))

    
    with open("requirements.txt", "w") as f:
        print('Create "requirements.txt"')
        for r in requirements:
            string = r[0] + '==' + r[1] + '\n'
            f.write(string)
            print("\t{}=={}".format(*r))
    print('"requirements.txt" was created.')
        
get_requirements()

Create "requirements.txt"
	pandas==1.2.4
	numpy==1.20.2
	matplotlib==3.3.4
"requirements.txt" was created.
